### ISSUE TITLE
Disconnect after some (mostly 60?) seconds + Solution

### ISSUE THREAD

**Issue by sycx2** [Slion/harmony#12]
Hey, to keep the connection alive you have to send ping messages in the form

`<iq type='get' id='ping-xxx'><ping xmlns='urn:xmpp:ping'/></iq>`

, where xxx is a unique id.

Just write a function to send this every minute and you'll be fine ;)

**Comment by Slion** [comment]
If I recall well there is a keep alive option you can use for that. It probably does the ping for you.
It's the second parameter in the client constructor.
See: https://github.com/Slion/harmony/blob/master/HarmonyHub/Client.cs#L82
